name: Update Stepik Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  update-stepik-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Update Stepik stats
        env:
          STEPIK_CLIENT_ID: ${{ secrets.STEPIK_CLIENT_ID }}
          STEPIK_CLIENT_SECRET: ${{ secrets.STEPIK_CLIENT_SECRET }}
          STEPIK_USER_ID: "486992310"
        run: python scripts/update_stepik.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/stepik-stats.svg

          git diff --cached --quiet || git commit -m "Update Stepik stats"
          git push